name: DevOps
on:
  push:
    branches: ['develop', 'master']
jobs:
  devops:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Unit & Integration Tests
        run: mvn -B verify
      - name: Sonar
          if: success()
          run: >
            mvn -B verify -X -DskipTests sonar:sonar
            -Dsonar.projectKey=victormartindz_iwvg-devops-martin-victor
            -Dsonar.organization=victormartindz
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=$SONAR_TOKEN
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
